import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  title: {
    fontSize: 22,
    color: '#16112B',
    marginRight: 5,
  },
  headerContainer: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    marginTop: 30,
    marginBottom: 20,
    backgroundColor: '#6C63FF',
    padding: 10,
  },
  balanceContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  balanceText: { fontSize: 18, color: '#FFF', marginBottom: 10 },
  amountText: { fontSize: 20, color: '#FFF', fontWeight: '600' },
  budgetContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 30,
  },
  budgetText: { fontSize: 20, color: '#FFF' },
  budgetAmount: { fontSize: 18, marginTop: 5, fontWeight: '600' },
  addButton: {
    position: 'absolute',
    bottom: 5,
    right: 10,
    backgroundColor: '#6C63FF',
    height: 50,
    width: 50,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  descriptionContainer: {
    backgroundColor: '#FFF',
    // padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  paymentContainer: {
    backgroundColor: '#F3F7FC',
    height: 100,
    borderRadius: 8,
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  amountTitle: {
    color: '#FFF',
    fontSize: 33,
    fontWeight: '800',
    marginTop: 10,
  },
  descriptionTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  dot: {
    height: 20,
    width: 20,
    borderRadius: 10,
    marginRight: 10,
  },
  paymentTitle: {
    color: '#080416',
    fontSize: 22,
    fontWeight: '600',
  },
  paymentCategory: {
    color: '#808080',
    fontSize: 15,
    fontWeight: '600',
  },
  reminder: {
    color: '#16112B',
    fontSize: 18,
    fontWeight: '600',
  },
  date: {
    color: '#808080',
    fontSize: 14,
    fontWeight: '600',
  },
  noPayment: {
    color: '#808080',
    fontSize: 22,
    fontWeight: '600',
  },
});
